CREATE TABLE catatan (
  id_catatan VARCHAR(50) PRIMARY KEY,
  deskripsi_catatan TEXT NOT NULL,
  waktu_dihubungi DATETIME NOT NULL,
  durasi TIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);